#!/data/data/com.termux/files/usr/bin/bash

echo -e "\n\033[0;32mSteamCMD Options \033[0;37m\n"
echo -e "\n1- Full SteamCMD launch configuration."
echo -e "2- Store Steam username (and password) for auto login."
echo -e "3- Login anonymously to Steam."
echo -e "4- Choose desired platform (Windows/Linux/MacOS)."
echo -e "5- Change the Steam directory (Where files are downloaded)."
echo -e "6- Manually edit the SteamCMD bin file."
echo -e "7- Exit.\n"

read -p "Select an option:" option
case $option in
1) ./option_scripts/steam_login.sh
./option_scripts/steam_platform.sh
./option_scripts/steam_installdir.sh
echo -e
exit;;

2) ./option_scripts/steam_login.sh
echo -e
exit;;

3) cd $PREFIX/var/lib/proot-distro/installed-rootfs/debian/root/.steamcmd_config
rm usrdata 2> /dev/null
echo "+login anonymous" >> usrdata
cd
echo -e
exit;;

4) ./option_scripts/steam_platform.sh
echo -e
exit;;

5) ./option_scripts/steam_installdir.sh
echo -e
exit;;

6) echo -e "\nIf you are not familiar with nano, here are a couple of commands to get you going:\n"
echo -e "Press \033[0;36mCTRL+O \033[0;37m(CTRL is on the termux keyboard) and \033[0;36mEnter\033[0;37m to save.\nPress \033[0;36mCTRL+X \033[0;37mto exit.\n"
read -n 1 -s -r -p "Press any key to continue."
echo -e "\n\n"
nano $PREFIX/var/lib/proot-distro/installed-rootfs/debian/bin/steamcmd
exit;;

7) echo -e "Exiting..\n"
exit;;

*) echo -e "Invalid option. Exiting..\n"
exit;;
esac
